# 人工產生異常

try:

	raise BaseException("錯誤原因")   # raise ErrorType(" Error Message ")
  
except(Exception,ex):

	print(Exception,":",ex)


# 斷言
self.assertEqual(ret,'OK')


